Add "SVG" support to download options
AykutSarac/jsoncrack.com pull request #204
Opened 2022-09-25 19:23 UTC by dogukanuhn

Hello,

I saw an issue named "[BUG]: export png is blurry and unreadable compared to web UI" and i thought, there should be and SVG option.

It is working fine in my local but maybe there should be some css edits.

2022-09-25 19:24 UTC, dogukanuhn commented
https://github.com/AykutSarac/jsoncrack.com/issues/194

2022-10-03 06:17 UTC, AykutSarac requested changes

2022-10-03 06:17 UTC, AykutSarac commented on src/components/FileInput/index.tsx
> +    value:string | number | readonly string[] | undefined,
Please change it to `value?: string | number | readonly string[]`

2022-10-03 06:17 UTC, AykutSarac commented on src/components/FileInput/index.tsx
> +    onChange: React.ChangeEventHandler<HTMLInputElement> | undefined,
here too

2022-10-03 06:17 UTC, AykutSarac commented on src/components/FileInput/index.tsx
> +    setExtension: Function,
Function is too general decleration, can we use `setExtension: (...params) => return type` here

2022-10-03 06:17 UTC, AykutSarac commented on src/containers/Modals/DownloadModal/index.tsx
> +      downloadURI(dataURI, `${fileDetails.filename}.${Extensions[extension]}`);
Would `${fileDetails.filename}.${extension}` do the job here?

2022-10-03 06:17 UTC, AykutSarac commented on src/containers/Modals/DownloadModal/index.tsx
> +              setExtension={(ext:number)=> setExtension(ext)}
Let's use `setExtension={setExtension}` here

2022-10-03 06:17 UTC, AykutSarac commented on src/containers/Modals/DownloadModal/index.tsx
> +              extensions={Object.keys(Extensions).filter((v) => isNaN(Number(v)))}
Could it be written in more simpler way?

2022-10-04 08:25 UTC, closed without merging