Added feature to indicate the user if the content JSON is exploitable…
AykutSarac/jsoncrack.com pull request #366
Opened 2023-11-14 19:47 UTC by tusharkc

Feature : #279 

Under this PR, I have created a function that will check if the JSON is exploitable or not, and if it is not exploitable, a new indication has been added to the bottom bar component, that will indicate that JSON is 100% safe.

2023-11-14 22:07 UTC, TallTed commented on src/containers/Editor/BottomBar.tsx
> +            Json is not exploitable
```suggestion
            JSON is not exploitable
```

2023-11-15 03:47 UTC, tusharkc commented
@TallTed I have added changes as per your suggestions.

2023-11-16 03:34 UTC, tusharkc commented
@TallTed The improvements have been added, I had accidentally clicked on the close button, but now the pr is open again.

2023-11-16 20:40 UTC, TallTed commented
@tusharkc — I'm just a contributing community member. My coding language is English, and I mostly poke at human-facing things. I have no other involvement in this project.

2023-12-17 12:39 UTC, AykutSarac requested changes

2023-12-17 12:39 UTC, AykutSarac commented on src/containers/Editor/BottomBar.tsx
> +  const contents = useFile(state => state.contents);
Each time the contents in updated it will cause a rerender which is a performance concern for us. Instead we could make our calculations with in `useFile(state => ...)` to prevent rerender and only when the value is changed, referred as *exploitable*.

2023-12-17 12:39 UTC, AykutSarac commented on src/containers/Editor/BottomBar.tsx
> +        )}
It's better to show the warning when it's **exploitable** instead of **not exploitable**.

2023-12-17 12:39 UTC, AykutSarac commented on src/containers/Editor/BottomBar.tsx
> +        )}
Also we could use "Exploitable" instead of "JSON is exploitable" so it will consume less space.

2023-12-17 12:40 UTC, AykutSarac commented
Good job, I've added a few comments!

2023-12-18 18:20 UTC, tusharkc commented
@AykutSarac I will work on these issues now.

2023-12-18 18:48 UTC, tusharkc commented
@AykutSarac https://github.com/AykutSarac/jsoncrack.com/pull/366/commits/c41836af82c9a63deddcddf16e93ec6f6ef36ecf


here is the pr with the reviews.

2024-09-29 11:58 UTC, closed without merging