fix: Zoom label not updating on selection/input
AykutSarac/jsoncrack.com pull request #389
Opened 2024-02-05 12:23 UTC by Shahidullah-Muffakir

**### Issue**:

This pull request addresses the issue where the zoom label next to the zoom dropdown and input field does not update to reflect the selected zoom level (Issue #388 ).

### Description:

This PR implements a fix that ensures the zoom label accurately displays the chosen zoom level, regardless of whether it's selected from the dropdown or entered in the input field.

### Changes:
Added a code block that dynamically updates the viewport in real-time as the user adjusts the zoom level. 
Because we are displaying the zoomFactor propery of viewport in the zoom label which was not updating

This enhancement ensures immediate synchronization between the user's zoom actions and the displayed viewport. Prior to this update, the viewport did not reflect changes in zoom levels promptly, resulting in the display of outdated information on the zoom label.

2024-02-05 12:32 UTC, AykutSarac commented
Good job! There's one issue remaining though, if we zoom in/out within the graph it's still showing incorrect value.

2024-02-05 12:34 UTC, Shahidullah-Muffakir commented
Got it, will look into it.

2024-02-05 22:46 UTC, Shahidullah-Muffakir commented
Hi AykutSarac,

I've investigated the issue with the zoom label not updating correctly when zooming within the graph. I've made some changes to address this.

Could you please take a look at the updated commit and let me know if this resolves the issue?

Thanks,

2024-02-07 10:20 UTC, Shahidullah-Muffakir commented
1. Fixed bug where zoom level label was not updating when using regular mouse wheel to zoom. It previously only updated on ctrl + wheel zoom. Now consistently updates on all zoom interactions.

2. Added debouncing of 300ms to zoom change handler. This limits how often the zoom level state and label are updated when user is quickly scrolling. Improves performance.

3. Zoom level state is now properly set whether user is zooming with ctrl or regular scroll. Resolved inconsistent behavior.

2024-02-07 11:05 UTC, AykutSarac requested changes

2024-02-07 11:05 UTC, AykutSarac commented on src/store/useGraph.ts
We may not need them as we attached debounced watcher to onUpdate to `<Space />` component.

2024-02-07 13:02 UTC, AykutSarac approved these changes

2024-02-07 14:00 UTC, merged